
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome
homeassistant_latitude: 104.67510
homeassistant_longitude: 35.32681
homeassistant_elevation: 84

recorder_db_url: mysql://homeassistant:REDACTED/homeassistant?charset=utf8mb4
nas_host: 127.0.0.1

#philhawthorne/ha-dockermon
restart_container: curl http://REDACTED/container/home-assistant/restart

#plex
plex_token: REDACTED
plex_port: REDACTED

#imac
imac_wol_mac: REDACTED
imac_wol_host: REDACTED
imac_off: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "tell app \"System Events\" to shut down" 2>/dev/null'
imac_sleep: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "tell app \"System Events\" to sleep" 2>/dev/null'
imac_restart: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "tell app \"System Events\" to restart" 2>/dev/null'
imac_cpu: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED top -l 1 | awk '/CPU usage/ {print $7}' 2>/dev/null
imac_mem: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED ps -A -o %mem | awk '{ mem += $1} END {print mem}' 2>/dev/null
imac_uptime: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED sysctl -n kern.boottime | awk '{print $4}' 2>/dev/null
imac_ip: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED curl icanhazip.com || echo 0

#monitors
monitors_mute_on: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "set volume with output muted" 2>/dev/null'
monitors_mute_off: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "set volume without output muted" 2>/dev/null'
monitors_mute_state: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "output muted of (get volume settings)"' || echo false
monitors_volume_slider: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "set volume output volume {{ states('input_number.monitors_volume') | int }} --100%" 2>/dev/null'
monitors_update_volume: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED 'osascript -e "output volume of (get volume settings)"' || echo 0
monitors_calibrate_monitors: |-
  ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED osascript <<EOF
    tell application "System Events"
      click menu bar item 1 of menu bar 2 of application process "SoundID Reference"
      click menu item "KRK (28 Sep)" of menu 1 of menu bar 2 of application process "SoundID Reference"
    end tell
  EOF
monitors_calibrate_headphones: |-
  ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED osascript <<EOF
    tell application "System Events"
      click menu bar item 1 of menu bar 2 of application process "SoundID Reference"
      click menu item "Beyerdynamic DT 990 Pro 250 Ohm Wired Av..." of menu 1 of menu bar 2 of application process "SoundID Reference"
    end tell
  EOF

#vacuum
xiaomi_vacuum_host: REDACTED
xiaomi_vacuum_token: REDACTED
xiaomi_cloud_username: REDACTED
xiaomi_cloud_password: REDACTED

#rpi
rpi_poweroff: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED sudo shutdown -h now 2>/dev/null
rpi_reboot: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED sudo reboot 2>/dev/null
rpi_led_off: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED "sudo sh -c 'echo 0 > /sys/class/leds/led0/brightness' && sudo sh -c 'echo 0 > /sys/class/leds/led1/brightness'"
rpi_cpu: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED top -bn 1 | grep "Cpu(s)" | awk '{print 100 - $8}' 2>/dev/null
rpi_mem: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED free | grep Mem | awk '{print $3 / $2 * 100}' 2>/dev/null
rpi_sd: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED df / | awk '{print $5}' | tail -n 1 2>/dev/null
rpi_uptime: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED uptime -s 2>/dev/null
rpi_ping_host: REDACTED
rpi_monitor_docker_url: tcp://REDACTED

#unifi
unifi_ip: REDACTED
unifi_port: REDACTED
unifi_user: REDACTED
unifi_pass: REDACTED

#github
github_username: REDACTED
github_access_token: REDACTED

#updates
updates_kemper: |-
  ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa REDACTED /opt/homebrew/bin/python3 GitHub/kemper-version/main.py || \
  echo '{"profiler_latest": "", "profiler_installed": "", "rigmanager_latest": "", "rigmanager_installed": ""}'

#switchbot
switchbot_mqtt_command: homeassistant/switch/switchbot/REDACTED/set
switchbot_mqtt_state: homeassistant/switch/switchbot/REDACTED/state
switchbot_mqtt_battery: homeassistant/switch/switchbot/REDACTED/battery-percentage
